#!/bin/bash
# Copyright (c) 2015, Tracerneo
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

# Depends on rotate-display
old="0"
while true; do
    if [ -e /sys/devices/platform/hp-wmi/tablet ]; then
        new=`cat /sys/devices/platform/hp-wmi/tablet`
        if [ "$new" != "$old" ]; then
            if [ $new == "1" ]; then
                rotate-display half
            elif [ $new == "0" ]; then
                rotate-display none
            fi
            old=$new
        fi
    fi
    sleep 0.5s
done
